```{r}
library(ggplot2)
library(reshape2)
library(dplyr)
library("Synth")
library(tidyverse)
library(numDeriv)
library(tseries)
library('alabama')
library("rgenoud")
```

```{r}

taux_change <- read_csv("taux_change.csv")
```

```{r}
lignedata=c('X1995', 'X1996', 'X1997', 'X1998', 'X1999', 'X2000', 'X2001', 'X2002', 'X2003', 'X2004', 'X2005', 'X2006', 'X2007', 'X2008', 'X2009', 'X2010', 'X2011', 'X2012', 'X2013', 'X2014', 'X2015', 'X2016', 'X2017')#les colonnes de données 
date=seq(2000, 2017)
```

```{r}
autre_pays=read.csv("WB_data2.csv")

autre_pays=autre_pays%>% filter(Country.Name %in% c("France","Canada","Brasil","Mexico","Cuba","China","India","Russia","Korea, Rep.","South Africa","Nigeria","Algeria","Morocco","Australia","Japan","New Zealand","Turkey","Israel", "Italy", "Sweden", "Denmark", "Poland", "Belgium", "Netherlands","Switzerland" ))

autre_pays <- autre_pays %>% select(-c(Pays_indic, `Country.Name`, `Indicator.Name`)) %>% pivot_longer(c(2:25), names_to = "year", values_to = "value") %>% pivot_wider(names_from = "Simple.Indicator", values_from = "value") 
autre_pays$year=as.numeric(substr(autre_pays$year, 2, 6))
id <- as.data.frame(count(autre_pays,Country.Code))  %>% select(-n)
id[,'id_country']=as.numeric(c(1:length(unique(autre_pays$Country.Code))))
autre_pays<-as.data.frame(inner_join(autre_pays,id))
autre_pays$id_country=as.integer(autre_pays$id_country)
autre_pays$year=as.numeric(autre_pays$year)
df_BM=autre_pays
```




```{r}
donn2010=df_BM%>%filter(year==2010)%>%select('Country.Code','gdb_hab')%>%rename(gdp_hab2010=gdb_hab)
df_BM=df_BM%>%left_join(donn2010,on="Country.Code")

df_BM$gdp_hab_ind=(df_BM$gdb_hab/df_BM$gdp_hab2010)*100
```

```{r}
variable=c("exports_rate","gdb_hab","FBCF","labor_force")

dataprep.out=Synth::dataprep(foo=df_BM,
                predictors = (variable),#Les variables utilisées en contrôle
                time.predictors.prior = c(2000:2011), #période pré-traitement
                special.predictors = list(list("gdb_hab",2010:2011,"mean"),
                                          list("gdb_hab",2004:2006,"mean"),
                                          list("gdb_hab",2007,"mean")),
                dependent="gdb_hab", #variable d'intérêt
                unit.variable = 'id_country', #colonne avec les index des pays
                unit.names.variable="Country.Code", #nom des pays
                treatment.identifier = 8, # n° de l'unité traitée
                controls.identifier = c(1:7,9:15), #n° des unités de contrôles
                time.variable = 'year', #colonne où se trouve la date
                time.optimize.ssr = 1995:2011, #période de maximisation
                time.plot=1999:2018 ) #période tracée sur le graphique


synth.out <- Synth::synth(data.prep.obj = dataprep.out, method = c("BFGS"))

Synth::path.plot(synth.res = synth.out, dataprep.res = dataprep.out,
Ylab = "Emploi indice 100", Xlab = "year", Legend = c("France", "synthetic France"), Legend.position = "bottomleft")

synth.tables <- Synth::synth.tab(dataprep.res = dataprep.out,
 synth.res = synth.out)

synth.tables$tab.pred
synth.tables$tab.v
```



```{r}
gen_liste=function(liste_value, date=c(list(2000:2007), list(2008:2011), 2012))
{
a=0

for(i in liste_value ){
  for (j in date){
    a=a+1
    if(a==1){liste=list(list(i,j, "mean"))}
    
    else{liste=c(liste, list(list(i, j, "mean")))  }
  }
}
liste=as.list(liste)

return(liste)
}

```








```{r}
prepaplot = function(synth_out = Synth::synth(data.prep.obj = dataprep.out, method = "BFGS"), 
                    synth_tables = Synth::synth.tab(dataprep.res = dataprep.out,synth.res = synth.out),
                    df = df_synth, 
                    n_countries = nb_country_plot,
                    date_inf = date_plot_inf,
                    date_sup = date_plot_sup,
                    valeur = liste_value[1],
                    treated_unit = pays){
  #synth_out : vaut synth.out, la sortie de l'optimisation via le package synth à représenter
  #synth_tables : vaut synth.tables, la sortie de l'optimisation via le package synth à représenter
  #df : la dataframe exploité pour faire le contrôle synthétique, afin de récupérer les bonnes valeurs des pays
  #n_countries : le nombre de pays contributeurs au contrefactuel que l'on souhaite représenter
  #date_inf : la date de début du graphique
  #date_sup : la date de fin du graphique
  #valeur : l'indicateur qui fait l'objet du contrôle synthétique
  #treated_unit : le pays sur lequel on effectue le contrôle synthétique
  
  indic = unique(subset(df, Country.Code == treated_unit)['id_country'])[1, 1]
  solpoids = synth_out$solution.w
  poids1=synth_tables$tab.w%>%rename(poids=w.weights)
  poids1 = poids1%>%rename(Country.Code=unit.names)
  poids1 = poids1[order(poids1$poids, decreasing=TRUE),]
  df_synth = df
  
  dfstrat = data.frame()

  for (countries in unique(poids1$Country.Code)){
          for (i in 1:length(unique(df_synth$Country.Code))){ 
            #On sépare maintenant selon si le pays a un indice plus petit que celui d'intérêt, ou plus grand, pour bien attribuer le poids correspondant au bon indice 
            if (countries == unique(df.melt$Country.Code)[i] & df.melt[df.melt$Country.Code==countries,]$id_country <indic){
              for (years in date_inf:date_sup){
              newrow = data.frame(valeur=df_synth[df_synth$Country.Code==countries & df_synth$year==years,][,valeur]*solpoids[i],
                            id_country=unique(df_synth[df_synth$Country.Code==countries,]$id_country),
                            Country.Code=countries,
                            weight = solpoids[i],
                            year = years)
              dfstrat = rbind(dfstrat, newrow)}}
            
            if (countries == unique(df.melt$Country.Code)[i] & df.melt[df.melt$Country.Code==countries,]$id_country >ind_pays){
              for (years in date_inf:date_sup){
              newrow = data.frame(valeur=df_synth[df_synth$Country.Code==countries & df_synth$year==years,][,valeur]*solpoids[i-1],
                            id_country=unique(df_synth[df_synth$Country.Code==countries,]$id_country),
                            Country.Code=countries,
                            weight = solpoids[i-1],
                            year = years)
              dfstrat = rbind(dfstrat, newrow)}}
            }  
  }
  
  
  #On crée maintenant le df avec les valeurs cumulées des contributions de chaque pays
  dfstratfin = data.frame()
  for (years in date_inf:date_sup){#on initialise
    i=1
    newrow = dfstrat[dfstrat$Country.Code == unique(dfstrat$Country.Code)[1] & dfstrat$year == years,]$valeur
    temp_df = data.frame(valeur=newrow,
                         id_country=unique(df_synth[df_synth$Country.Code==unique(dfstrat$Country.Code)[1],]$id_country),
                         Country.Code=unique(dfstrat$Country.Code)[1],
                         weight = dfstrat[dfstrat$Country.Code == unique(dfstrat$Country.Code)[1] & dfstrat$year == years, ]$weight,
                         year = years)
    temp_df$Legende = paste(i, '. ', temp_df$Country.Code, ' (',  round(temp_df$weight, digits = 3), ')' )
    dfstratfin = rbind(dfstratfin, temp_df)
    
    for (countries in unique(dfstrat$Country.Code)[2:n_countries]){ #on garde ceux les plus élevés
      i=i+1
      newrow = newrow + dfstrat[dfstrat$Country.Code == countries & dfstrat$year == years, ]$valeur
      
      temp_df = data.frame(valeur=newrow,
                           id_country=unique(df_synth[df_synth$Country.Code==countries,]$id_country),
                           Country.Code=countries,
                           weight = dfstrat[dfstrat$Country.Code == countries & dfstrat$year == years, ]$weight,
                           year = years)
      temp_df$Legende = paste(i, '. ', temp_df$Country.Code, ' (',  round(temp_df$weight, digits = 3), ')' )
      dfstratfin = rbind(dfstratfin, temp_df)
    }}
  
  
  
  #On rajoute l'unité synthétique
  for (years in date_inf:date_sup){
    newrow = dfstrat[dfstrat$Country.Code == unique(dfstrat$Country.Code)[1] & dfstrat$year == years,]$valeur
    for (countries in unique(dfstrat$Country.Code)[2:length(unique(dfstrat$Country.Code))]){ #on rajoute les petites valeurs
      newrow = newrow + dfstrat[dfstrat$Country.Code == countries & dfstrat$year == years, ]$valeur}
    temp_df = data.frame(valeur=newrow,
                            id_country=0,
                            Country.Code='Unité synthétique',
                            year = years,
                            weight = 1)
    temp_df$Legende = paste(temp_df$Country.Code)
    dfstratfin = rbind(dfstratfin, temp_df)
  }
  dfstratfin = dfstratfin[order(dfstratfin$weight, decreasing=TRUE),]
  
  
  #On ajoute la vraie valeur pour la France
  for (years in date_inf:date_sup){
    temp_df = data.frame(valeur=df_synth[df_synth$Country.Code == treated_unit & df_synth$year == years,][,valeur],
                         Country.Code= 'Unité traitée',
                         year=years,
                         weight = 1,
                         id_country = indic)
    temp_df$Legende = paste('',temp_df$Country.Code)
    dfstratfin=rbind(dfstratfin, temp_df)}
  
  dfstratfin = dfstratfin[order(dfstratfin$weight, decreasing=TRUE),]
  
  return(dfstratfin)
  }
```

#Fonction qui fait le plut cumulatif

```{r}
stratplot = function(df = dfstratfin,
                     synth_colors = 'Blues',
                     treated_color = 'red', 
                     name = plot_title,
                     y_name = ordonnee_name){
  #df : le df sorti par la fonction prepaplot
  #synth_color : la palette de couleur utilisée pour les contributions à l'unité synthétique
  #treated_color : la couleur de l'unité traitée
  #name : le titre du graphique, à remplir en string
  #y_name : le nom de l'ordonnée, en string également
  min = 10 - length(unique(df[df$Country.Code != 'Unité traitée',]$Country.Code))
  pal = c(brewer.pal(n = 9, name = synth_colors)[min:9], treated_color)
  
  lines = c(rep('dashed', length(df[df$Country.Code != 'Unité traitée',]$Country.Code)), rep('solid', length(df[df$Country.Code == 'Unité traitée',]$Country.Code)))
  
  colorplot = ggplot(data=df,aes(x=year, y=valeur))+
    geom_point(data=df, aes(group=Legende, col=Legende), show.legend = TRUE) +
    geom_line(data=df, aes(group=Legende, col=Legende), linetype = lines, show.legend = TRUE) +
    scale_color_manual(values = pal) +
  
    #On met une barre verticale pour séparer avant et après le traitement
    geom_vline(xintercept = 2012.5, colour = 'grey', size = 1, linetype = 'dashed') +
    
    #On règle les paramètres d'esthétique généraux
    labs(title = name,
         x = "Année",
         y = y_name) +
    theme_minimal()

  print(colorplot)
}
```




##FONCTION QUI FAIT DE L'ANALYSE UNIVARIEE
```{r}
univariate_synth=function(liste_value, df_synth=df_BM, pays='FRA', date_opti_inf = 2000,date_opti_sup = 2012, ordonnee = NA, date_plot_inf = 1998, date_plot_sup = 2016, nb_country_plot = 5, colorgraph = TRUE, ordonnee_name, plot_title){

  #liste_value : la variable sur laquelle on optimise, au format c('nom de colonne')
  #df_synth : nom du df où sont les variables
  #pays : donner le code qui identifie le pays à traiter
  #date_plot_inf : date de début du graphique
  #date_plot_sup : date de fin du graphique
  #date_opti_inf : date de début de la période d'optimisation du fit
  #date_opti_sup : date de fin de la période d'optimisation du fit
  #ordonnee : donne le Ylim, soit le min et le max de l'ordonnee du plot, au format c(min,max)
  #nb_counttry_plot : le nombre de pays à plotter dans le graphique en couleur des contributions
  #colorgraph : si false, on ne fait  pas le graphique en couleur (pour aller un peu plus vite)


valeur=liste_value[1]
ind_pays= unique(subset(df_synth, Country.Code == pays)['id_country'])[1, 1]

### ON EFFECTUE UN CONTROLE SYNTHÉTIQUE UNIVARIÉ
dataprep.out=Synth::dataprep(foo=df_synth,
                predictors.op = "mean", #La manière dont on les prend en compte
                time.predictors.prior = date_opti_sup, #période pré-traitement
                special.predictors = gen_liste(liste_value, date_opti_inf, date_opti_sup),
                dependent=valeur, #variable d'intérêt
                unit.variable = "id_country", #colonne avec les index des pays
                unit.names.variable="Country.Code", #nom des pays
                treatment.identifier = ind_pays, # n° de l'unité traitée
                controls.identifier = c(unique(subset(df_synth, Country.Code!= pays)['id_country'])[,1]), #n° des unités de contrôles
                time.variable = 'year', #colonne où se trouve la date
                time.optimize.ssr = date_opti_inf:date_opti_sup, #période de maximisation
                time.plot=date_plot_inf:date_plot_sup) #période tracée sur le graphique

synth.out <- Synth::synth(data.prep.obj = dataprep.out, method = "BFGS")

#ON TRACE LE GRAPHIQUE CLASSIQUE DU PACKAGE SYNTH
Synth::path.plot(synth.res = synth.out, dataprep.res = dataprep.out,
Ylab = liste_value[1], Xlab = "year", Legend = c(pays, paste('synthetic',pays)), Legend.position = "bottomright", Ylim = ordonnee)
synth.tables <- Synth::synth.tab(dataprep.res = dataprep.out,synth.res = synth.out)

#ON RECUPERE LES POIDS ET ON LES TRIE
poids1=synth.tables$tab.w%>%rename(poids=w.weights)
poids1 = poids1%>%rename(Country.Code=unit.names)
poids1 = poids1[order(poids1$poids, decreasing=TRUE),]


###  GRAPHIQUES EN COULEURS

if (colorgraph == TRUE){
  dfstratfin = prepaplot(synth_out = synth.out, 
                         synth_tables = synth.tables,
                         df = df_synth,
                         n_countries = nb_country_plot,
                         date_inf = date_plot_inf,
                         date_sup = date_plot_sup,
                         valeur = liste_value[1],
                         treated_unit = pays)

  stratplot(df = dfstratfin,
            synth_colors = 'Blues',
            treated_color = 'red', 
            name = plot_title,
            y_name = ordonnee_name)
}
return(poids1)
}
```
```{r}
univariate_synth(c('gdb_hab'), ordonnee_name ='Valeur Ajoutée par habitant', plot_title = "Trajectoire de la France réelle et contrefactuelle, \net contributions des différents pays à l'unité contrefactuelle")
```

```{r}
df_stratTitouanBM=function(df.melt=df_BM, liste_value='gdb_hab', pays='FRA', date0=2000, date1=2005, date2=2012, date3=2016, ordonnee = NA, nb_country_plot = 5, synthdon=FALSE, synth.out=0, dataprep.out=0){
valeur=liste_value[1]
ind_pays= unique(subset(df.melt, Country.Code == pays)['id_country'])[1, 1]
dateopti = date0:date3

if(synthdon==FALSE){
dataprep.out=Synth::dataprep(foo=df.melt,
                predictors.op = "mean", #La manière dont on les prend en compte
                time.predictors.prior = date2, #période pré-traitement
                special.predictors = gen_liste(liste_value, c(date1:2009,2011:date2)),
                dependent=liste_value[1], #variable d'intérêt
                unit.variable = 'id_country', #colonne avec les index des pays
                unit.names.variable="Country.Code", #nom des pays
                treatment.identifier = ind_pays, # n° de l'unité traitée
                controls.identifier = c(unique(subset(df.melt, Country.Code!=pays)['id_country'])[,1]), #n° des unités de contrôles
                time.variable = 'year', #colonne où se trouve la date
                time.optimize.ssr = dateopti, #période de maximisation
                time.plot=date0:date3) #période tracée sur le graphique

synth.out <- Synth::synth(data.prep.obj = dataprep.out, method = "BFGS")


Synth::path.plot(synth.res = synth.out, dataprep.res = dataprep.out,
Ylab = liste_value[1], Xlab = "year", Legend = c(pays, paste('synthetic',pays)), Legend.position = "bottomright", Ylim = ordonnee)}
synth.tables <- Synth::synth.tab(dataprep.res = dataprep.out,synth.res = synth.out)
poids1=synth.tables$tab.w%>%rename(poids=w.weights)
poids1 = poids1%>%rename(Country.Code=unit.names)
poids1 = poids1[order(poids1$poids, decreasing=TRUE),]
solpoids=synth.out$solution.w
dfstrat = data.frame()

for (countries in unique(poids1$Country.Code)){
  print(countries)
        for (i in 1:length(unique(df.melt$Country.Code))){ 
          #On sépare maintenant selon si le pays a un indice plus petit que celui d'intérêt, ou plus grand, pour bien attribuer le poids correspondant au bon indice 
          
          if (countries == df.melt$Country.Code[df.melt$id_country==i] & i <ind_pays){
            for (years in date0:date3){
            newrow = data.frame(valeur=df.melt[df.melt$Country.Code==countries & df.melt$year==years,][,valeur]*solpoids[i], Country.Code=countries, index=unique(df.melt[df.melt$Country.Code==countries,]$id_country), weight = solpoids[i], year = years)
            dfstrat = rbind(dfstrat, newrow)}}
          
          if (countries == df.melt$Country.Code[df.melt$id_country==i] & i >ind_pays){
            for (years in date0:date3){
            newrow = data.frame(valeur=df.melt[df.melt$Country.Code==countries & df.melt$year==years,][,valeur]*solpoids[i-1], Country.Code=countries, index=unique(df.melt[df.melt$Country.Code==countries,]$id_country),  weight = solpoids[i-1], year = years)
            dfstrat = rbind(dfstrat, newrow)}}
          }  
}


#On crée maintenant le df avec les valeurs cumulées des contributions de chaque pays
dfstratfin = data.frame()
for (years in date0:date3){#on initialise
  newrow = dfstrat[dfstrat$Country.Code == unique(dfstrat$Country.Code)[1] & dfstrat$year == years,]$valeur
  temp_df = data.frame(valeur=newrow, Country.Code=unique(dfstrat$Country.Code)[1], year = years, id_country=unique(df.melt[df.melt$Country.Code==unique(dfstrat$Country.Code)[1],]$id_country), 
weight = dfstrat[dfstrat$Country.Code == unique(dfstrat$Country.Code)[1] & dfstrat$year == years, ]$weight)
  dfstratfin = rbind(dfstratfin, temp_df)
  
  for (countries in unique(dfstrat$Country.Code)[2:nb_country_plot]){ #on garde ceux les plus élevés
    newrow = newrow + dfstrat[dfstrat$Country.Code == countries & dfstrat$year == years, ]$valeur
    
    temp_df = data.frame(valeur=newrow, id_country=unique(df.melt[df.melt$Country.Code==countries,]$id_country), Country.Code=countries, 
weight = dfstrat[dfstrat$Country.Code == countries & dfstrat$year == years,]$weight, year = years)
    dfstratfin = rbind(dfstratfin, temp_df)
  }}



#On rajoute l'unité synthétique
for (years in date0:date3){
  newrow = dfstrat[dfstrat$Country.Code == unique(dfstrat$Country.Code)[1] & dfstrat$year == years,]$valeur
  for (countries in unique(dfstrat$Country.Code)[2:length(unique(dfstrat$Country.Code))]){ #on rajoute les petites valeurs
    newrow = newrow + dfstrat[dfstrat$Country.Code == countries & dfstrat$year == years, ]$valeur}
  temp_df = data.frame(valeur=newrow, id_country=0, Country.Code='Synthetic Unit', weight = 1, year = years)
  dfstratfin = rbind(dfstratfin, temp_df)
}
dfstratfin = dfstratfin[order(dfstratfin$weight, decreasing=TRUE),]


#On ajoute la vraie valeur pour la France
for (years in date0:date3){
  temp_df = data.frame(valeur=df.melt[df.melt$Country.Code == pays & df.melt$year == years,][,valeur], Country.Code= pays, year=years, weight = 1, id_country = ind_pays)

  dfstratfin=rbind(dfstratfin, temp_df)}

colorplot = ggplot(data=dfstratfin,aes(x=year, y=valeur))+
  geom_line(aes(group=Country.Code, col=Country.Code))

print(colorplot)
}

```
```{r}
unique(poids1$Country.Code)
```

```{r}
simpleSynthBM=function(liste_value, df.melt=df_BM, pays='FRA', dateplot=1997:2016, dateopti=2000:2012){
special=list()

year=seq(dateopti[1],dateopti[length(dateopti)],2)
ind_pays=as.numeric(df.melt[df.melt$Country.Code=='FRA',]$id_country[1])
#Version avec les différentes dates version Synth
dataprep.out=Synth::dataprep(foo=df.melt,
                predictors.op = "mean", #La manière dont on les prend en compte
                time.predictors.prior = 2012, #période pré-traitement
                special.predictors = gen_liste(liste_value),
                dependent=liste_value[1], #variable d'intérêt
                unit.variable = "id_country", #colonne avec les index des pays
                unit.names.variable="Country.Code", #nom des pays
                treatment.identifier = ind_pays, # n° de l'unité traitée
                controls.identifier = c(1:max(df.melt$id_country))[-ind_pays], #n° des unités de contrôles
                time.variable = 'year', #colonne où se trouve la date
                time.optimize.ssr = dateopti, #période de maximisation
                time.plot=dateplot) #période tracée sur le graphique

synth.out <- Synth::synth(data.prep.obj = dataprep.out, method = "BFGS")

Synth::path.plot(synth.res = synth.out, dataprep.res = dataprep.out,
Ylab = liste_value[1], Xlab = "year", Legend = c(pays, paste('synthetic',pays)), Legend.position = "bottomright")
synth.tables <- Synth::synth.tab(dataprep.res = dataprep.out,synth.res = synth.out)
poids1=synth.tables$tab.w%>%rename(poids=w.weights)
print(poids1)}
```



```{r}
simpleSynthBM(c('gdp_hab_ind', 'exports_hab', 'unemployment rate'))
```


```{r}
simpleSynthBM(c('unemployment rate', 'gdb_hab', 'exports_hab' ))
```




```{r}
numinit=1
nbre_pays=max(df_BM$id_country)
d=c(1:nbre_pays)
liste_value=c('unemployment rate', 'gdb_hab', 'exports_hab' )
numFR=as.numeric(df_BM[df_BM$Country.Code=='FRA',]$id_country[1])

for (i in d)
{
  #On calcul le contrôle synthétique avec l'unité i traitée
  print(i)
  if(i==1){ind_ctrl=c(2:nbre_pays)}
  else{
    if(i==nbre_pays){ind_ctrl=c(1:(i-1))}
    else{ind_ctrl=c(1:(i-1),(i+1):nbre_pays)}
    }
  dataprep_i.out=Synth::dataprep(foo=df_BM,
                predictors = liste_value,
                special.predictors = gen_liste(liste_value),
                time.predictors.prior = 2000:2011, 
                dependent=liste_value[1], 
                unit.variable = "id_country", #colonne avec les index des pays
                unit.names.variable="Country.Code", #nom des pays
                treatment.identifier = i, 
                controls.identifier =   ind_ctrl, 
                time.variable = 'year', 
                time.optimize.ssr = 2000:2010, #
                time.plot=1999:2016) 

quiet(synth.out_i <- Synth::synth(data.prep.obj = dataprep_i.out, method = "BFGS")) #On calcul les résultats sans les afficher

#Synth::gaps.plot(synth.res = synth.out_i, dataprep.res = dataprep_i.out,Ylab = "PIB", Xlab = "year")

  if (i==numinit) { #On initialise une base avec en ligne le noms de l'unité puis l'effet du traitement pour chaque année (le numéro de l'année n'est pas dans la base)
    noms=c(rep(as.character(i),nrow(dataprep_i.out$Y0)))
    valeur=dataprep_i.out$Y1-dataprep_i.out$Y0%*%synth.out_i$solution.w 
    df=data.frame(noms,valeur)
    couleur=c("red") #ca c'est pour gérer les couleurs 
  }
  
  if (i>numinit) {  #On complète la base
    noms=c(noms,rep(as.character(i),nrow(dataprep_i.out$Y0)))
    valeur=c(valeur,dataprep_i.out$Y1-dataprep_i.out$Y0%*%synth.out_i$solution.w)
    df=data.frame(noms,valeur)
    if (i==numFR){couleur=c(couleur,"blue")}
    else{couleur=c(couleur,"red")}}

}
    
df
df2=data.frame(x=(rep((1999:2016),length(unique(noms)))),df)
df_effe=filter(df2,x>2008)
```




```{r}
df2$noms=as.numeric(df2$nom)
df_RMPSE=df2%>%rename(id_country=noms)%>%left_join(df_BM[c("Country.Code","id_country")][d,])
df_RMPSE$valeur_sq=df_RMPSE$valeur*df_RMPSE$valeur
RMPSE_res=group_by(df_RMPSE,id_country)%>% summarise(RMPSE_tot = mean(valeur_sq),Country.Code=unique(Country.Code))
RMPSE_res$RMPSE_trait=(group_by(filter(df_RMPSE,x>2012),id_country)%>% summarise(mean = mean(valeur_sq),Country.Code=unique(Country.Code)))$mean
RMPSE_res$RMPSE_prev=(group_by(filter(df_RMPSE,x<2013),id_country)%>% summarise(mean = mean(valeur_sq),Country.Code=unique(Country.Code)))$mean
```


```{r}
pays=unique(df_BM[c('id_country','Country.Code')])

RMPSE_2=RMPSE_res[-3]
RMPSE_res=RMPSE_2%>%left_join(pays)
RMPSE_res
```

```{r}
pays=unique(df_BM[c('id_country','Country.Code')])

RMPSE_2=RMPSE_res[-3]
RMPSE_res=RMPSE_2%>%left_join(pays)
RMPSE_res%>%mutate(RMPSE_tot=sqrt(RMPSE_res$RMPSE_tot),
                   RMPSE_trait=sqrt(RMPSE_res$RMPSE_trait),
                   RMPSE_res=sqrt(RMPSE_res$RMPSE_prev)) %>%select(Country.Code,RMPSE_tot,RMPSE_trait,RMPSE_prev)
RMPSE_res$RMPSE_ajuste=RMPSE_res$RMPSE_trait/RMPSE_res$RMPSE_prev
RMPSE_res%>%arrange(-RMPSE_res$RMPSE_ajuste)

RMPSE_res%>%arrange(-RMPSE_res$RMPSE_ajuste)
```


```{r}
df2$noms=as.character(df2$noms)
qplot(x=x, y=valeur,color=noms, data=df2, geom="line",ylim=c(-20,25))+ xlab("Date") +scale_color_manual(breaks = unique(df2$noms),                        values=couleur)
df_BM
```
