---
title: "R Notebook"
output: html_notebook
---
Récupération des données

```{r}
library(ggplot2)
library(reshape2)
library("tseries")
```
```{r}
capital=read.csv("C:/Users/sylva/Desktop/git/Statap_cice/Statistical_Capital.csv")
croiss=read.csv("C:/Users/sylva/Desktop/git/Statap_cice/Statistical_Growth-Accounts.csv")
travail=read.csv("C:/Users/sylva/Desktop/git/Statap_cice/Statistical_Labour.csv")

compte=read.csv("C:/Users/sylva/Desktop/git/Statap_cice/Statistical_National-Accounts.csv")
description=read.csv("C:/Users/sylva/Desktop/git/Statap_cice/Variable-Description.csv")

```


```{r}
lignedata=c('X1995', 'X1996', 'X1997', 'X1998', 'X1999', 'X2000', 'X2001', 'X2002', 'X2003', 'X2004', 'X2005', 'X2006', 'X2007', 'X2008', 'X2009', 'X2010', 'X2011', 'X2012', 'X2013', 'X2014', 'X2015', 'X2016', 'X2017')#les colonnes de données
date=seq(1995, 2015)
```

```{r}
ligne_pays<-function(base,vari,codei,pays,variable='var')
{
tableau=subset(base,var==vari& code==codei)[c("country", lignedata)] 
rownames(tableau)<-tableau[,1]
tableau<-tableau[,-1]
tableau<-t(tableau)
tabeleau<-tableau[,pays]
df <- data.frame(x=1995:2017, data.frame(tabeleau))
df.melted <- melt(df, id="x")
qplot(x=x, y=value, color=variable, data=df.melted, geom="line")+ xlab("Date") + ylab(variable)
}
```

```{r}
ligne_pays( compte, vari="VA", codei='TOT',pays=c("FR", "DE","UK", "ES", "IT") )+ ggtitle("évolution de la production dans les grands pays européens") +
  xlab("année") + ylab("Valeur ajoutée, en millions d'euros/livres")
```

```{r}
ligne_pays( compte, vari="EMP", codei='TOT',pays=c("FR", "DE","UK", "ES", "IT") )+ ggtitle("évolution de l'emploi dans les grands pays européens") +
  xlab("année") + ylab("nombre d'emplois en milliers")
```

```{r}
ligne_pays( croiss, vari='LAB', codei='TOT', pays=c("FR", "DE", "UK", "ES", "IT") )+ ggtitle("évolution du coût du travail dans les grands pays européens") +
  xlab("année") + ylab("coût du travail en millions d'euros")
```



###Tests unitaires###

Les tests pour une la France :

```{r}
tableau=subset(croiss,var=='LAB' & code=='TOT'& country=='FR')[lignedata]
serietemp=c(log(tableau))
```


```{r}
adf.test(serietemp)
```


```{r}
serietempnum=as.numeric(serietemp)
PP.test(serietempnum)
```

```{r}
kpss.test(serietemp)
```

Les trois tests sont cohérents( ils n'ont pas le même H_0) : le log de la série de l'emploi total en France est bien stationnaire.


Les fonctions généralisant les tests : 
Il reste à les mettre en log !


```{r}
prepadonnees<- function(base, vari, codei){
tableau=subset(base,var==vari & code==codei)[c("country", lignedata)] 
rownames(tableau)<-tableau[,1]
tableau<-tableau[,-1]
tableau<-t(tableau)
tableau=data.frame(tableau)
tableau
}#cette fonction permet de créer la database sur laquelle faire les tests

tableau=prepadonnees(croiss, 'LAB', 'TOT')
```


```{r}
multi_stat_tests<- function(tableau){
    p <- ncol(tableau)
    df_multi <- data.frame(var=names(tableau),
adf.pvalue=sapply(tableau, function(x) adf.test(log(x)[!is.na(x)],alternative = "stationary")$p.value),#on fait un test par colonne
kpss.pvalue=sapply(tableau, function(x) kpss.test(log(x)[!is.na(x)])$p.value),
PP.pvalue=sapply(tableau, function(x) PP.test(log(x)[!is.na(x)])$p.value)
                           )
    df_multi$adf <- df_multi$adf.pvalue < 0.05
    df_multi$kpss <- df_multi$kpss.pvalue < 0.05#son H_O est différent donc ce n'est pas ça qu'on cherche en réalité (je crois)
    df_multi$PP <- df_multi$PP.pvalue < 0.05
    df_multi
}
```
```{r}
multi_stat_tests(prepadonnees(croiss, 'LAB', 'TOT'))
multi_stat_tests(prepadonnees(compte, 'VA', 'TOT'))
multi_stat_tests(prepadonnees(compte, 'EMP', 'TOT'))
```








